### ISSUE TITLE
dateFormat

### ISSUE THREAD

**Issue by elyphas** [OutWatch/outwatch-libs#1]
What would be the way to pass a `dateFormat` parameter?

**Comment by cornerman** [comment]
Fixed with 7429a0b0fad32953cab2d9d0745d9e3c814a342c

I have added a `format` option to the `flatpickr` method: `flatpickr(..., format = Some(formatString))` and added another method to provide the full `FlatpickrOptions` object in case you want to configure more: `flatpickrWithOptions(..., options)`.

**Comment by elyphas** [comment]
Thank you

**Comment by cornerman** [comment]
@elyphas Currently, the selected date value is only emitted when the picker is closed. if you want this whenever it changes, we can discuss how to change the interface. let me know!

**Comment by elyphas** [comment]
Ok thank you.
